<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <!-- Genera il pacchetto .algo installabile in cTrader -->
    <ProducesAlgo>true</ProducesAlgo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.*" />
  </ItemGroup>

</Project>
